### PR TITLE
Enhancements on email console logging

### PR DESCRIPTION
**Pull request by niwinz**

### CODE REVIEW

**Comment by luwol03** [comment]
Why was that pr closed?

**Comment by niwinz** [comment]
It is closed because it was replaced with other that already included the changes #1792

**Comment by luwol03** [comment]
Oh ok. Thank you for your very quick answer. Then I should be able to have this changes in the next release? Is that already planned?

**Comment by niwinz** [comment]
yes, we will bump a minor release soon (next week we have holidays here in spain) so probably first days of the following week

**Pull request closed without merging**
