### PR TITLE
Redesign Team members

### PR DESCRIPTION
**Pull request by EvaMarco**
This PR solve this [task](https://tree.taiga.io/project/penpot/task/2324) of this [US](https://tree.taiga.io/project/penpot/us/2283)

Accidentally this PR solves this [issue](https://tree.taiga.io/project/penpot/us/2760)

### CODE REVIEW

**Comment by superalex** [comment]
- Logged as an owner if I try to change my own role to admin or editor there is an error shown. Also If I try to change my role to the same one (owner) there is a lightbox appearing that shouldn't be shown (as I'm not really doing any change)

**Comment by EvaMarco** [comment]
> 

I've removed that option, it's not logical to remove the ownership like that. If you want to quit being an owner, set this role to someone and you will be admin.

**Comment by superalex** [comment]
Thanks @EvaMarco it works great

Now I've detected one more situation. If I create a new team and then leave it (without adding any more members) I receive a "Unexpected validation error" error

**Comment by EvaMarco** [comment]
Thanks, @superalex I could find the bug and fix it.

**Pull request merged**
