### PR TITLE
Update locales.json

### PR DESCRIPTION
**Pull request by iblueer**
Add Simplified Chinese translation some.

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

### CODE REVIEW

**Comment by niwinz** [comment]
Looks very nice! I will merge it in some instants together with some other internal improvements on the i18n module.

**Comment by niwinz** [comment]
One question @iblueer 
is this correct?
image

**Comment by iblueer** [comment]
Yes, correct perfectly.

**Comment by iblueer** [comment]
> One question @iblueer 
> 
> is this correct?
> 
> image
> 
> 
Yes, correct perfectly

**Comment by niwinz** [comment]
thanks!, merged with many other fixes; feel free to open more patches

**Pull request closed without merging**
