### PR TITLE
🐋 Add environment variables for specifying the export and backend url

### LINKED ISSUE #2984: How to set the backend url for frontend docker image?
Hi, My team has an internal app called penpot-backend, and as such we aren't able to use the compose one. Is there an environment variable to change this? 

Your reply is appreciated. Thanks in advance!

### PR DESCRIPTION
**Pull request by Supernova3339**
This PR is for the `frontend` docker image.
`penpotapp/frontend`

> Why was this change made?

When deploying Penpot, I use a weird docker combination that doesn't use compose files.
Penpot has the URLs hardcoded by default into the `nginx.conf` which is bad practice.

[Documentation PR](https://github.com/penpot/penpot-docs/pull/134)

closes #2984

### CODE REVIEW

**Comment by niwinz** [comment]
Hi @Supernova3339 

Nice catch, looks a nice change, but I need to double check it and test it. I will go with this as fast as I finish with my current stuff I'm working on. 

Thanks

**Comment by Supernova3339** [comment]
> Hi @Supernova3339
> 
> Nice catch, looks a nice change, but I need to double check it and test it. I will go with this as fast as I finish with my current stuff I'm working on.
> 
> Thanks

Thanks for the reply! Considering these values are hardcoded, not very good coding standards. Sent a PR to fix it. If you find anything that concerns you, please let me know. I did NOT touch anything that was commented out.

**Comment by niwinz** [comment]
I'm pretty happy with your changes, I just need test it myself and then merge. I'll probably will do it tomorrow.
I'm honestly not 100% sure if you can use environment variables as-is in the nginx.conf file; that's why I really want to try it.

**Comment by Supernova3339** [comment]
I can link you to an example repo if needed. That's how I found out about
this

**Comment by abn0mad** [comment]
Hi there, I was also looking for a way to specify the backend and exporter URLs for a similar reason; running penpot as a series of rootless podman containers managed by systemd.

Won't this pull require something along the lines of [this](https://www.baeldung.com/linux/nginx-config-environment-variables) in order to work though?

i.e.

```
/bin/bash -c "envsubst '$${BACKEND_URL} $${EXPORTER_URL}' < /etc/nginx/nginx.conf.template > \ 
/etc/nginx/nginx.conf && nginx -g 'daemon off;'"

```

It would be great to see the option to specify the backend and exporter URLs for users of podman and users who prefer to stay away from docker-compose.

**Comment by Supernova3339** [comment]
> Hi there, I was also looking for a way to specify the backend and exporter URLs for a similar reason; running penpot as a series of rootless podman pods managed by systemd.
> 
> Won't this pull require something along the lines of [this](https://www.baeldung.com/linux/nginx-config-environment-variables) in order to work though?
> 
> i.e.
> 
> ```
> /bin/bash -c "envsubst '$${BACKEND_URL} $${EXPORTER_URL}' < /etc/nginx/nginx.conf.template > \ 
> /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
> 
> ```
> 
> It would be great to see the option to specify the backend and exporter URLs for users of podman and users who prefer to stay away from docker-compose. 

Not at all! I've tested it and my solution works perfectly. It's better to NOT overcomplicate things :)

**Comment by abn0mad** [comment]
@Supernova3339 - Thanks for the quick reply :), well that's good news, I didn't know environment variables could be accepted by nginx in such a way, that opens up a lot of simplified deployments indeed. I look forward to having this pull request being accepted :) (and sorry for raising the question unnecessarily).

**Comment by niwinz** [comment]
image

As I suspected, this does not work out of the box. Nginx does not support interpolation of environment variables out of the box. This is a screenshot of the nginx docker image readme:

image

It is posible to have this functionality but an additional step is necessary. I will look on how to approach this

**Comment by niwinz** [comment]
https://github.com/penpot/penpot/pull/3010 replaces this PR,
thanks for the suggestion

**Pull request closed without merging**
