### PR TITLE
Add server CORS env var in doc

### PR DESCRIPTION
**Pull request by madmath03**
:memo: Add server CORS env var in doc

@niwinz I saw you added CORS settings, so I add the documentation that goes with it.

By the way, I do not know if it's still in progress or CORS should be working, but I cannot contact the backend due to CORS error `The Same Origin Policy disallows reading the remote resource at http://localhost:6060/api/auth/login` even though I'm working on http://localhost:3449.

### CODE REVIEW

**Comment by niwinz** [comment]
Hmm, the CORS should be working :(

In any case CORS is only needed for development environment, in production environment everything is running under the same domain.

Can you paste the complete error you have? 

PD: setting up correctly cors is just :hankey: ... xD

**Comment by madmath03** [comment]
Yeah, CORS is always a pain to setup properly 😅 
Since the devenv would not work, I switched to the production mode and use the frontend-dbg you added (really useful by the way).

I will share more logs when I find some time to test again.

**Comment by madmath03** [comment]
**Backend**:

Absolutely no logs on call 😐 
I should probably try to increase the log level but will do later.

**Client logs**:
<details>

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:6060/api/auth/login. (Reason: CORS request did not succeed).
2
on-error: {:status 0, :payload ""} ui.cljs:58:3
    uxbox$main$ui$on_error ui.cljs:58
    store store.cljs:20
    potok$core$handle_error core.cljs:122
    2 core.cljc:1120
    RxJS 25
    beicon$core$create_$_sink core.cljc:260
    beicon$core$create_$_sink core.cljc:264
    G__11281__1 core.cljs:4306
    G__11281 core.js:15047
    uxbox$util$http$fetch_$_on_complete http.cljs:77
    fireListeners eventtarget.js:284
    dispatchEventInternal_ eventtarget.js:381
    dispatchEvent eventtarget.js:196
    dispatchErrors_ xhrio.js:731
    onReadyStateChangeHelper_ xhrio.js:873
    onReadyStateChangeEntryPoint_ xhrio.js:813
    onReadyStateChange_ xhrio.js:797
undefined ui.cljs:59:3
    uxbox$main$ui$on_error ui.cljs:59
    store store.cljs:20
    potok$core$handle_error core.cljs:122
    2 core.cljc:1120
    RxJS 25
    beicon$core$create_$_sink core.cljc:260
    beicon$core$create_$_sink core.cljc:264
    G__11281__1 core.cljs:4306
    G__11281 core.js:15047
    uxbox$util$http$fetch_$_on_complete http.cljs:77
    fireListeners eventtarget.js:284
    dispatchEventInternal_ eventtarget.js:381
    dispatchEvent eventtarget.js:196
    dispatchErrors_ xhrio.js:731
    onReadyStateChangeHelper_ xhrio.js:873
    onReadyStateChangeEntryPoint_ xhrio.js:813
    onReadyStateChange_ xhrio.js:797
```

</details>

**Client request**:
<details>

```
Request URL:http://localhost:6060/api/auth/login
Request method:OPTIONS
Referrer Policy:no-referrer-when-downgrade
```

</details>

**Client request headers**:
<details>

```
Host: localhost:6060
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Referer: http://127.0.0.1:3449/
Origin: http://127.0.0.1:3449
Connection: keep-alive

```

</details>

**Comment by niwinz** [comment]
I'll try to run the same setup than you and try to find the problem.

PD: I merge this PR  ;)

**Pull request merged**
