### PR TITLE
Docker containers, bug fix and translations

### LINKED ISSUE #94: Add Travis CI
:construction_worker: Add automated build of docker image with Travis CI

### LINKED ISSUE #95: Remove postgre from Docker
uxbox docker image should not contain postgre and rather provide a docker-compose setup with a specific postgre service, at least for a "_production_" environment.

### PR DESCRIPTION
**Pull request by madmath03**
This PR is a compilation of all the work we did on our side while waiting for the developments here to restart.
Everything is not finished but at least nothing that was previously working has been broken so far.
This was originally created from the `master` branch but I'm sending this to your `wip` branch if you want to review/change it on your side before merging to master

Content of this PR (might not be exhaustive): 
* :sparkles: Introduction of "production-ready" docker containers for backend and front end. Each container contains a released version of each component. Containers are using a common base image we developed: https://github.com/Monogramm/docker-uxbox-builder. Containers are currently available on our DockerHub ([monogramm/uxbox](https://hub.docker.com/r/monogramm/uxbox/)) and links in README will need to be updated once you create your own public docker images;
* :sparkles: Introduction of a docker-compose file with all the needed services and using the "production-ready" containers (will close #95);
* :sparkles: Rework of manage.sh to execute unit tests (backend tests still missing because need running pgsql), build of previously mentioned production containers and run of docker-compose;
* :construction_worker: Introduction of CI mechanisms (Travis CI) to close #94 : CI is setup to execute all manage.sh targets and ensure they end successfully.
* :globe_with_meridians: Added several missing translations and replaced some hard coded texts with new translations (added French translations while at it)
* :wrench: Added a few configuration properties (issue #92 for instance), making possible to setup  almost all the application through (docker) environment variables
* :bug: Fixed a really nasty bug in copy/paste and undoable actions management
* :memo: Updated the README with some information for easier setup of development environment docker configuration
* :iphone: Fixing CSS and some actions to make the app compatible with touch screens (mostly for tablet, smartphones would require a whole lot of work to dynamically hide uneeded sections)
* :lipstick: Fixed some SCSS variables and improved the (hidden but still found) UXBOX dark theme (looks absolutely great, by the way)
* :bento: Added some default colors in the store : UXBOX colors (I like the idea of providing the users the very colors / icons / images that make UXBOX beautiful), Bootstrap colors set, Material Design Colors by "theme", Social Media colors
* :construction: Tried (but failed to finish) to restore the defaults Material Design icons. I believe it is a great feature to provide users with well known set of icons like Material / FontAwesome / IcoMoon, and if possible UXBOX own icons
* :construction: Tried (but failed to finish) to fully replace the designer's colors palette actions navigation: it's kind of annoying to move left / right colors one by one... using a scroll bar, you can more quickly navigate, it's compatible with touch screens and it's easy in JS to have the buttons change the scroll position to keep the same initial behavior (but ClojureScript keeps trolling me and not doing what I expect from it...)

### CODE REVIEW

**Comment by niwinz** [comment]
awesome work! i will need some time for review it!

**Comment by niwinz** [comment]
A have reviewed all the changes and first of all, awesome work!

I have only one concern, the "production" docker stuff, I think that it is a little bit opinionated on how you are/want deploy it (that is not bad), is just abour organization, i prefer on the main code base maintain only developer related stuff, the specific deployment related scripts and docker, from my point of view should live probably separated in an other directory or repository. 

What do you think about that?

**Comment by madmath03** [comment]
Hello @niwinz ,

Thank you for reviewing this (huge) PR.
I fully understand your point about separating the code base from the Dockerfile.
Keeping it in the same directory was easier and I admit I was too lazy to improve it.

If we aim to separate development and production/deployment stuff, I think the best would be to have a separate repository: it could provide several versions or variant of UXBOX (alpine, debian, etc...) and later become an [official docker image](https://docs.docker.com/docker-hub/official_images/).

I think we can provide such a repository fairly quickly as we're quite used to work with official docker containers like [WordPress](https://github.com/docker-library/wordpress) or [NextCloud](https://github.com/nextcloud/docker), but if we aim to have an official docker image the repository should be part of the UXBOX organization.

We will experiment on our side with 2 repositories (`docker-uxbox-front` and `docker-uxbox-back`) and remove the docker containers from this PR.
Once the docker containers are ready and stable, you can decide if you want to retrieve them to later make an official image 😉

**Comment by niwinz** [comment]
Hello @madmath03 
Nice!
I'm already working on updating all the build stuff (replace leiningen with clojure cli tools) and updating all the docker stuff (look at the branch `build-refactor`); it is already on top of the changes of this PR.

Let's iterate on the docker part after build-refactor is merged on master, at this moment i maintain all the docker files in the repository, only changing the location.

**Comment by niwinz** [comment]
My changes to the docker part they are mainly your Dockerfiles, with simplified build step and minor changes on the "production docker images". The main changes:
- replace leiningen with clojure cli tools
- rename the development (tmux based) docker image to `devenv`
- update the devenv image removing ad-hoc imagemagick build (mainly simplification changes)
- use the same (`devenv`) image to generate dist for frontend and backend apps (this avoid the need to maintain separated build image
- the backend production image now deploys as source (don't create fat jar file)
- the frontend production image now serves everything only on http (not https, the https part is delegated to a gateway not handled by uxbox)

**Comment by niwinz** [comment]
I close this PR, because I go to merge it manually together with the build-refactor branch.

**Pull request closed without merging**
