### PR TITLE
Artboard presets

### PR DESCRIPTION
**Pull request by girafic**
Added more artboard presets.

### CODE REVIEW

**Comment by niwinz** [comment]
Hi @girafic 

First of all, thanks for this contribution.

For merge this MR, we need you to accept the [DCO](https://github.com/penpot/penpot/blob/develop/CONTRIBUTING.md#developers-certificate-of-origin-dco) (the steps are very simple, just add `-s` to you `git commit`)

**Comment by girafic** [comment]
@niwinz DCO accepted

**Comment by niwinz** [comment]
@girafic nice, thanks! I will merge it today.

**Comment by niwinz** [comment]
Merged manually,  thanks!
image

**Pull request closed without merging**
