### PR TITLE
♻️ CSS refactor unification of selectors and values

### PR DESCRIPTION
**Pull request by ondrejkonec**
Hi, this is first PR for [this iniciative](https://community.penpot.app/t/penpot-app-design-frontend-improvements/2559/2?u=ondrejkonec). 

In this PR, I'm trying to unify corner radius across the app. What I did so far is that I only connect existing variables. What I think should be improved is merge some values.

## What is done
Connected existing properties for border-radius to UI elements.

## What can be improved
I would go through code and check similar elements and suggest new values. Since there are several corner radius values that cannot be recognized by eye, I would recommend merging few of them and **extend variable set**.

**Here is the analysis**, where you can see complete list:

border-analys

Since there are values that are very close, I would suggest new values as I already wrote.
similiar-radiuses

## How would I do it?
In this PR, I would post my suggestions in comment (comparing current vs. proposal) and I would wait for approval. There is example:
variant-1

variant-2

I'm not sure, who is designer responsible for UI and how would he/she imagine the UI to look (if more serious or rather friendly, etc.) and therefore I would not change anything for myself and it would probably be good to always discuss it.

If it's too much work, I can leave it as it is and just take care of the code changes. 

And I am also wondered if I couldn't create the elements directly in Penpot so that they can see the changes (if you use the component library or so). I will be happy to help in these areas as well, if you are interested. I'm not also sure if you work in Penpot when you design new features, but if not, I can make take care of this and create component library by myself and align this with code, because this is my passion.

I know that it's a little bit long comment and huge task, but I believe that it can help.

### CODE REVIEW

**Comment by ondrejkonec** [comment]
Hello guys! @myfunnyandy @EvaMarco @niwinz ... or another who should be mentioned?

When I started working on linking design variables, I realized that there would probably be a lot of changes in the code, so I would probably make smaller parts and create a branch for each. This branch might grow a lot over time, and then it would be difficult to do checks and deal with modifications at all.

Therefore, I would suggest to merge this branch and I would create a new one, for more specific modifications (this was a big bite). What do you think?

There is no design change (only one where I merged font size `25.6px` & `27px `with `26px`), so the merge is safe. 

**Goal of this kick-off changes** is connect what we have and see where we can improve UI and maybe remove some unnecessary code or made little visual changes in future, that can improve consistency.

**Comment by myfunnyandy** [comment]
Hi @ondrejkonec! 

I like the idea of advancing throung small, controlled, chunks but regarding branching I'd rather wait for @EvaMarco's advice.

You can keep the list of mentioned in @EvaMarco and myself, as we're the ones that have been following the initiative since the begining. This is public so anyone could still join anytime.

**Comment by EvaMarco** [comment]
Hi @ondrejkonec :

Sorry for the delay in my reply. I was able to read your changes the other day, they are very accurate. 
I would create separate branches and PR's for each block of changes, so we can manage and review them better.
Don't add any more changes to this one, so I can review and merge it this week. 

We are planning a big UI refactoring in the next few weeks, so I think it's best if you work on creating variables, (like you did with borders), removing unused code or creating keyframes with very repetitive code or things like that. 
What do you think?

**Comment by ondrejkonec** [comment]
@myfunnyandy Great, I'll continue the conversation between the three of us.

@EvaMarco No need to say sorry, there is no rush from my side, I just want to make it as clear as possible for you. And your idea sound good - I will not add anything here anymore and next time, I'll create branch like "connected FOO properties" or something like this to make it very clear for you.

If you feel that I could help with something about refactoring (e.g. implement naming convention into components, or edit individual UI elements on the basis of design), I will be happy to help. This is my favorite activity. 

Do you think, I can continue with new changes that will cover only a small part of the initiative?

**Comment by EvaMarco** [comment]
Hello @ondrejkonec 
Some considerations before merging this PR
You should name your commits according to our contrib code.
https://help.penpot.app/contributing-guide/code-contributions/#code-contributions-commits
We usually squash all commits into one or two to have a clean git log like this example.
Screenshot from 2023-02-21 16-35-10
You can merge your commits into one or two by splitting your changes into border radius and sources for example. 

The second thing we need, as you are contributing a lot of changes you must sign your commit with the Developer Certificate of origin, you can read more here https://help.penpot.app/contributing-guide/code-contributions/#code-contributions-dco

And the last thing, while you are working on your PR you can put it as a draft, I will be able to see the changes but I will know that it is still WIP. This way you can name your PR with the final name and not "WIP whatever".
When all this is modified we can merge.

Thank you very much

**Comment by ondrejkonec** [comment]
> Hello @ondrejkonec Some considerations before merging this PR You should name your commits according to our contrib code. https://help.penpot.app/contributing-guide/code-contributions/#code-contributions-commits We usually squash all commits into one or two to have a clean git log like this example. Screenshot from 2023-02-21 16-35-10 You can merge your commits into one or two by splitting your changes into border radius and sources for example.
> 
> The second thing we need, as you are contributing a lot of changes you must sign your commit with the Developer Certificate of origin, you can read more here https://help.penpot.app/contributing-guide/code-contributions/#code-contributions-dco
> 
> And the last thing, while you are working on your PR you can put it as a draft, I will be able to see the changes but I will know that it is still WIP. This way you can name your PR with the final name and not "WIP whatever". When all this is modified we can merge.
> 
> Thank you very much

Thank you Eva, this is great information for me. I already made all changes (expect the last one since PR is not draft anymore). I'm not sure if I have rights to put my PR as "draft", but I'll try next time. 

Is everything ok from your point of view?

**Comment by EvaMarco** [comment]
Hello @ondrejkonec:

We have merged this manually to add you in the thanks section.

**Comment by ondrejkonec** [comment]
@EvaMarco Thanks! Do you think I can continue? 

An btw. I am just curious - what is "thanks section"? :)

**Comment by myfunnyandy** [comment]
@ondrejkonec its a section that we add to the [dev diaries](https://penpot.app/dev-diaries) and the [changelog](https://github.com/penpot/penpot/blob/staging/CHANGES.md), which share the same content. Look for "Community contributions" to see some examples :)

**Comment by EvaMarco** [comment]
Hi @ondrejkonec:
You can continue with a new branch with the contents you like the most among the topics we discuss.
This Monday I'm going to start with our UI redesign and I'll be able to tell you more.
As Andy told you our thank you section is the way to thank contributors for their collaboration. In every release that an external contributor participates we add them to the changes file. 
In addition they usually appear in our dev diaries that you have in the web page.https://penpot.app/dev-diaries

**Comment by ondrejkonec** [comment]
Hi @EvaMarco & @myfunnyandy Thank you both for info and also thank you for mention in your dev diaries. I appreciate that! :)

**Comment by ondrejkonec** [comment]
> This Monday I'm going to start with our UI redesign and I'll be able to tell you more.

@EvaMarco I forgot to respond to this :) 
If you feel like I could help, I'd love to hear from you and I'd love to get involved.

**Pull request closed without merging**
