### PR TITLE
⚗️ Provide a Gitpod development environment

### PR DESCRIPTION
**Pull request by madmath03**
> Please provide enough information so that others can review your pull request:

:alembic: Provide a Gitpod development environment

> Explain the **details** for making this change. What existing problem does the pull request solve?

We've discovered [Gitpod](https://gitpod.io/) a few months ago and we think it might be really nice to have a FOSS development environment in the browser to contribute to Penpot.

This is still a work in progress as the startup tasks need to be fixed (race issues) and I cannot seem to be able to reach frontend, but I thought you might be interested to take a look.

[Open this branch in Gitpod](https://gitpod.io/#https://github.com/Monogramm/penpot/tree/madmath03/gitpod-setup)

FYI: @niwinz 

> Screenshots/GIFs

image

### CODE REVIEW

**Comment by niwinz** [comment]
Looks very interesting. 

I think we also need to think in a way to reuse some docker "instructions" because the gitpod looks very similar to the DEVENV and maintaining two separate dockerfiles that are practically the same... (in any case is a very minor issue for now, we can look on how to solve it later :D)

Ping when it ready to test, and if you need help.

**Comment by madmath03** [comment]
Hi @niwinz 

This PR is ready for review. Penpot devenv seems to be running correctly within Gitpod.
I also planned to add a bit of documentation in <https://github.com/penpot/penpot-docs/blob/main/technical-guide/developer/devenv.md>:

```markdown

## Development environment using Gitpod (experimental) ##

You can also use [GitPod](https://gitpod.io/) to run the local development environment: [![open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/penpot/penpot)

If you wish to sign your commits using GitPod, follow the instructions from [gitpod-io/gitpod#666](https://github.com/gitpod-io/gitpod/issues/666#issuecomment-534347856):

-   Convert your source `.gnugpg` directory contents to base64 data: `tar -czvf - ./.gnupg | base64 -w 0`
-   Place this data into a gitpod environment variable called `GNUGPG` (in your account [Gitpod > Settings](https://gitpod.io/settings/))
-   Get your source signing key: `gpg --list-secret-keys --keyid-format LONG`
-   Place this data into a gitpod environment variable called `GNUGPG_KEY` (in your account [Gitpod > Settings](https://gitpod.io/settings/))

```

You're right about the Dockerfile being very similar to the regular devenv. There is also a nginx.conf for gitpod which is very similar as well. It would certainly be a good thing to _merge_ them somehow.

Let me know if you have any questions.

**Comment by niwinz** [comment]
I'll review it today probably, in any case @madmath03, I think that we should squash all commits in a single one for this feature. I will do it myself after review.

In any case, great work!

**Comment by niwinz** [comment]
I have rebased it and pushed to a `Monogramm-madmath03/gitpod-setup` branch, just testing it, so I close this MR.

Thank you :heart: 
Looks very nice.

PD: I was very busy and I have priorized other tasks (mainly release preparation and bug fixes).

**Comment by niwinz** [comment]
@madmath03 After taking some time experimenting with this, i found that all the time i start new workspace, the services does not start 
image
But, if I just rerun them again, they starts successfully ... :S maybe I need to add some sleep  hehe

**Comment by niwinz** [comment]
seems like a good old sleep solves the issue hehehe

**Comment by niwinz** [comment]
you can look my chages on this MR: https://github.com/penpot/penpot/pull/807

**Comment by madmath03** [comment]
@niwinz I restored our branch because after looking at your `gitpod.yml`, I think you do not have the latest version of our code: <https://github.com/Monogramm/penpot/blob/madmath03/gitpod-setup/.gitpod.yml>

We already added `gp await-port ...` so that the different services would wait after starting.

**Comment by niwinz** [comment]
Yeah, i have removed it because in some cases the port waiting is useless; a good example is exporter, port start listening much before the build is ready. On `develop`  I have fixed it for exporter using `babashka` clojure variant for scripting. Now i'm playing with gitpod and reasearching why I get ENOENT...

**Comment by niwinz** [comment]
And on this case, the problem is that for some strange reason, the automatic start of `yarn` fails. But if I run it manually, everything seems ok :S  and yarn does not need any port wait...

**Comment by madmath03** [comment]
I also see the `npx -y` was removed so the services might not start until someone answers interactions (happened during our tests).

Also I see you removed the env var in dockerfile for SMTP settings. I guess penpot will not be able to contact and use MailHog then.

**Comment by madmath03** [comment]
> And on this case, the problem is that for some strange reason, the automatic start of `yarn` fails. But if I run it manually, everything seems ok :S and yarn does not need any port wait...

That's weird... I do not remember having this issue during our tests. Will check again.

**Comment by niwinz** [comment]
> Also I see you removed the env var in dockerfile for SMTP settings. I guess penpot will not be able to contact and use MailHog then.

I only removed the repeated entries
image

> I also see the npx -y was removed so the services might not start until someone answers interactions (happened during our tests).

On my tests the -y just fails; don't know why, didnt invesigated on it yet. I just found that removing the `-y` the command does not fails on manual run (automatic run failed as said before). In any case, we don't have any interactive comands there... in our local devenv we use all the time npx without `-y`.

**Comment by madmath03** [comment]
> > And on this case, the problem is that for some strange reason, the automatic start of `yarn` fails. But if I run it manually, everything seems ok :S and yarn does not need any port wait...
> 
> That's weird... I do not remember having this issue during our tests. Will check again.

And yeah, the port wait here was mostly a "_hack_" to ensure that services were ready and in particular that **frontend and exporter yarn do not run at the same time**.
Maybe that's why you see it works manually while it fails when running automatically.

A better fix for that would be to use `gp sync-wait` on a custom event:
```
  sync-await        Awaits an event triggered using gp sync-done
  sync-done         Notifies the corresponding gp sync-await calls that this event has happened
```

**Comment by niwinz** [comment]
Oh, nice hint, I go to try it.

**Comment by madmath03** [comment]
> Oh, nice hint, I go to try it.

Just sent you a suggestion on the new PR 😉

**Pull request closed without merging**
