### PR TITLE
Update es.po (change an existing translation)

### PR DESCRIPTION
**Pull request by Pablohn26**
Hi,

I would like to change the existing translation in Spanish. I know this should be done using Weblate but I make this PR to request translation access and remember the first changes that I want to change. 

This is my Transifex public profile: https://www.transifex.com/user/profile/Pablohn/

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

### CODE REVIEW

**Comment by girafic** [comment]
@Pablohn26 Please close this PR, for translations it is already created in Weblate (https://hosted.weblate.org/projects/penpot/). More info about contributing you will find here --> https://help.penpot.app/contributing-guide/translations/

**Comment by Pablohn26** [comment]
I opened this PR as that link mentions:

> Open a [github issue](https://github.com/penpot/penpot/issues) giving details about the language you want to translate (language), the type of translation (new language, new translation or change an existing translation) and your Weblate user.

> If everything is correct we will get back to you providing you permissions to the actions needed.

I did not mention that my Weblate user is `Pablohn26`, the same as Github

**Comment by Pablohn26** [comment]
Oh, I see I have already permission. Thanks!

**Comment by Pablohn26** [comment]
I still do not have permission to make suggestions

image

**Comment by niwinz** [comment]
You should have permissions now. Sorry for delay

**Pull request closed without merging**
